apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: mykafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers:
   - my-cluster-kafka-bootstrap.mykafka:9092 
  topics:
   - my-topic 
  sink: 
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eventinghello